services:
  api:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg://sensor:secret@db:5432/sensorhub
    depends_on:
      - db

  db:
    image: postgres:16 # imagen oficial de postgres
    ports:
      - "5432:5432" # puerto para exponer el servicio de postgres
    environment: 
    # variables de entorno para la configuracion 
    # del postgres que se usara en la aplicacion
      POSTGRES_USER: sensor
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: sensorhub
    volumes: # volumenes para persistir datos entre reinicios del 
     # contenedor y evitar la perdida de datos aunque el contenedor se elimine
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    