"""esquema inicial: sensors y readings

Revision ID: 0436696aa27b
Revises: 
Create Date: 2026-08-06 17:33:19.538726

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '0436696aa27b'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
